"""Constants for the Eneco peblar integration."""

DOMAIN = "peblar"
UPDATE_INTERVAL = 30


CHARGER_CURRENT_VERSION_KEY = "FirmwareVersion"
CHARGER_PART_NUMBER_KEY = "ProductPn"
CHARGER_SERIAL_NUMBER_KEY = "ProductSn"
CHARGER_SOFTWARE_KEY = "FirmwareVersion"
CHARGER_MAX_CHARGING_CURRENT_KEY = "ChargeCurrentLimit"
CHARGER_CHARGING_CURRENT_ACTUAL_KEY = "ChargeCurrentLimitActual"
CHARGER_TOTAL_ENERGY_KEY = "EnergyTotal"
CHARGER_CURRENT_PHASE1_KEY = "CurrentPhase1"
CHARGER_SESSION_ENERGY_KEY = "EnergySession"
CHARGER_CHARGE_POWER_KEY = "PowerTotal"

# CHARGER_ADDED_DISCHARGED_ENERGY_KEY = "added_discharged_energy"
# CHARGER_ADDED_ENERGY_KEY = "added_energy"
# CHARGER_ADDED_RANGE_KEY = "added_range"
# CHARGER_CHARGING_POWER_KEY = "charging_power"
# CHARGER_CHARGING_SPEED_KEY = "charging_speed"
# CHARGER_CHARGING_TIME_KEY = "charging_time"
# CHARGER_COST_KEY = "cost"
# CHARGER_CURRENT_MODE_KEY = "current_mode"
# CHARGER_CURRENT_VERSION_KEY = "currentVersion"
# CHARGER_CURRENCY_KEY = "currency"
# CHARGER_DATA_KEY = "config_data"
# CHARGER_DEPOT_PRICE_KEY = "depot_price"
# CHARGER_ENERGY_PRICE_KEY = "energy_price"
# CHARGER_FEATURES_KEY = "features"
# CHARGER_SERIAL_NUMBER_KEY = "serial_number"
# CHARGER_PART_NUMBER_KEY = "part_number"
# CHARGER_PLAN_KEY = "plan"
# CHARGER_POWER_BOOST_KEY = "POWER_BOOST"
# CHARGER_SOFTWARE_KEY = "software"
# CHARGER_MAX_AVAILABLE_POWER_KEY = "max_available_power"
# CHARGER_MAX_CHARGING_CURRENT_KEY = "max_charging_current"
# CHARGER_MAX_ICP_CURRENT_KEY = "icp_max_current"
# CHARGER_PAUSE_RESUME_KEY = "paused"
# CHARGER_LOCKED_UNLOCKED_KEY = "locked"
# CHARGER_NAME_KEY = "name"
# CHARGER_STATE_OF_CHARGE_KEY = "state_of_charge"
# CHARGER_STATUS_ID_KEY = "status_id"
# CHARGER_STATUS_DESCRIPTION_KEY = "status_description"
# CHARGER_CONNECTIONS = "connections"
